title: Fábio Ewerton
email: fabioew89@gmail.com
description: Mais um maravilhoso site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabio.eti.br" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed

# permalink: /:title:output_ext
permalink: /:title